version: '3.8'

services:
  kafka-1:
    image: apache/kafka:4.1.0
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - 29092:9092
      - 9997:9997
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" 
      # monitoring
      KAFKA_JMX_PORT: 9998
      KAFKA_JMX_HOSTNAME: kafka-1
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Djava.rmi.server.hostname=kafka-1 \
        -Dcom.sun.management.jmxremote.port=9997 \
        -Dcom.sun.management.jmxremote.rmi.port=9997"
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=9997:/opt/jmx-exporter/kafka.yml
    volumes:
      - ./data/kafka-1:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter 

  kafka-2:
    image: apache/kafka:4.1.0
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - 39092:9092
      - 9998:9998
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:19092,PLAINTEXT_HOST://localhost:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" 
      # monitoring
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka-2
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Djava.rmi.server.hostname=kafka-2 \
        -Dcom.sun.management.jmxremote.port=9998 \
        -Dcom.sun.management.jmxremote.rmi.port=9998"
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=9998:/opt/jmx-exporter/kafka.yml
    volumes:
      - ./data/kafka-2:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter

  kafka-3:
    image: apache/kafka:4.1.0
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - 49092:9092
      - 9999:9999
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:19092,PLAINTEXT_HOST://localhost:49092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" 
      # monitoring
      KAFKA_JMX_PORT: 1000
      KAFKA_JMX_HOSTNAME: kafka-3
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Djava.rmi.server.hostname=kafka-3 \
        -Dcom.sun.management.jmxremote.port=9999 \
        -Dcom.sun.management.jmxremote.rmi.port=9999"
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=9999:/opt/jmx-exporter/kafka.yml
    volumes:
      - ./data/kafka-3:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter


  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - 8081:8081
      - 9185:9185
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:19092,PLAINTEXT://kafka-2:19092,PLAINTEXT://kafka-3:19092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      # monitoring
      JMX_PORT: 9181
      SCHEMA_REGISTRY_JMX_OPTS: >-
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=9185:/opt/jmx-exporter/kafka.yml

    volumes:
      - ./data/schema-registry:/var/lib/schema-registry
      - ./jmx-exporter:/opt/jmx-exporter

  connect-1:
    image: confluentinc/cp-kafka-connect:7.5.3
    container_name: connect-1
    env_file:
      - .env
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
    ports:
      - 8083:8083
      - 9105:9105
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:19092,kafka-3:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-1
      CONNECT_REST_ADVERTISED_PORT: 8083
      CONNECT_REST_ADVERTISED_LISTENER: http
      CONNECT_LISTENERS: http://0.0.0.0:8083
      CONNECT_GROUP_ID: connect-cluster

      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs-v2
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets-v2
      CONNECT_STATUS_STORAGE_TOPIC: connect-status-v2

      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3

      CONNECT_CONFIG_PROVIDERS: env
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: org.apache.kafka.common.config.provider.EnvVarConfigProvider
      CONNECT_CONFIG_PROVIDERS_ENV_PARAM_ALLOWLIST_PATTERN: ^MYSQL_.*

      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/plugins

      CONNECT_ERRORS_RETRY_TIMEOUT: -1
      CONNECT_RETRIES: 2147483647
      CONNECT_RETRY_BACKOFF_MS: 10000

      # monitoring
      JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: connect-1
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Djava.rmi.server.hostname=connect-1 \
        -Dcom.sun.management.jmxremote.port=9101 \
        -Dcom.sun.management.jmxremote.rmi.port=9101"
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=9105:/opt/jmx-exporter/kafka.yml


    volumes:
      - ./plugins:/etc/kafka-connect/plugins
      - ./jmx-exporter:/opt/jmx-exporter

  connect-2:
    image: confluentinc/cp-kafka-connect:7.5.3
    container_name: connect-2
    env_file:
      - .env
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
    ports:
      - 8084:8084
      - 9106:9106
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:19092,kafka-3:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-2
      CONNECT_REST_ADVERTISED_PORT: 8084
      CONNECT_REST_ADVERTISED_LISTENER: http
      CONNECT_LISTENERS: http://0.0.0.0:8084
      CONNECT_GROUP_ID: connect-cluster

      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs-v2
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets-v2
      CONNECT_STATUS_STORAGE_TOPIC: connect-status-v2

      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3

      CONNECT_CONFIG_PROVIDERS: env
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: org.apache.kafka.common.config.provider.EnvVarConfigProvider
      CONNECT_CONFIG_PROVIDERS_ENV_PARAM_ALLOWLIST_PATTERN: ^MYSQL_.*

      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/plugins

      CONNECT_ERRORS_RETRY_TIMEOUT: -1
      CONNECT_RETRIES: 2147483647
      CONNECT_RETRY_BACKOFF_MS: 10000

      # monitoring
      JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: connect-2
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Djava.rmi.server.hostname=connect-2 \
        -Dcom.sun.management.jmxremote.port=9102 \
        -Dcom.sun.management.jmxremote.rmi.port=9102"
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=9106:/opt/jmx-exporter/kafka.yml
 
    volumes:
      - ./plugins:/etc/kafka-connect/plugins
      - ./jmx-exporter:/opt/jmx-exporter

  connect-3:
    image: confluentinc/cp-kafka-connect:7.5.3
    container_name: connect-3
    env_file:
      - .env
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
    ports:
      - 8085:8085
      - 9107:9107
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:19092,kafka-3:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-3
      CONNECT_REST_ADVERTISED_PORT: 8085
      CONNECT_REST_ADVERTISED_LISTENER: http
      CONNECT_LISTENERS: http://0.0.0.0:8085
      CONNECT_GROUP_ID: connect-cluster

      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs-v2
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets-v2
      CONNECT_STATUS_STORAGE_TOPIC: connect-status-v2

      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3

      CONNECT_CONFIG_PROVIDERS: env
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: org.apache.kafka.common.config.provider.EnvVarConfigProvider
      CONNECT_CONFIG_PROVIDERS_ENV_PARAM_ALLOWLIST_PATTERN: ^MYSQL_.*

      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/plugins

      CONNECT_ERRORS_RETRY_TIMEOUT: -1
      CONNECT_RETRIES: 2147483647
      CONNECT_RETRY_BACKOFF_MS: 10000

      # monitoring
      JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: connect-3
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Djava.rmi.server.hostname=connect-3 \
        -Dcom.sun.management.jmxremote.port=9103 \
        -Dcom.sun.management.jmxremote.rmi.port=9103"
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=9107:/opt/jmx-exporter/kafka.yml


    volumes:
      - ./plugins:/etc/kafka-connect/plugins
      - ./jmx-exporter:/opt/jmx-exporter

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - connect-1
      - connect-2
      - connect-3
      - schema-registry

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
