global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-1'
    static_configs:
      - targets: ['kafka-1:9997']

  - job_name: 'kafka-2'
    static_configs:
      - targets: ['kafka-2:9998']

  - job_name: 'kafka-3'
    static_configs:
      - targets: ['kafka-3:9999']

  - job_name: 'connect-1'
    static_configs:
      - targets: ['connect-1:9101']

  - job_name: 'connect-2'
    static_configs:
      - targets: ['connect-2:9102']

  - job_name: 'connect-3'
    static_configs:
      - targets: ['connect-3:9103']

  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:9181']
